### ISSUE TITLE
Snapshot crawl fails

### ISSUE THREAD

**Issue by DANIELKAKAI** [geelen/react-snapshot#120]
Error: Uncaught [TypeError: Cannot read property 'bind' of undefined]
    at reportException (/usr/local/lib/node_modules/react-snapshot/node_modujsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/usr/local/lib/node_modules/react-snapshot/node_mos/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)

**Comment by groteworld** [comment]
I just came across this too? Did you figure out your issue @DANIELKAKAI?
