### ISSUE TITLE
Error when building when <canvas /> is being used

### ISSUE THREAD

**Issue by ca-miked** [geelen/react-snapshot#123]
Hi,

I'm getting a canvas element error message when trying to build a project that is using a <canvas /> tag. Per the error message, I installed the canvas npm package but this did not resolve the error.

> Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)

Any ideas/suggestions on a fix or workaround?

Thanks

**Comment by ca-miked** [comment]
Here's the more detailed stack trace

> 🕷   Starting crawling http://localhost:52417/
Error: Not implemented: HTMLCanvasElement.prototype.getContext (without installing the canvas npm package)
    at module.exports (/Users/.../create-react-app-router/node_modules/jsdom/lib/jsdom/browser/not-implemented.js:9:17)
    at HTMLCanvasElementImpl.getContext (/Users/.../create-react-app-router/node_modules/jsdom/lib/jsdom/living/nodes/HTMLCanvasElement-impl.js:42:5)
    at HTMLCanvasElement.getContext (/Users/.../create-react-app-router/node_modules/jsdom/lib/jsdom/living/generated/HTMLCanvasElement.js:30:56)

**Comment by ca-miked** [comment]
Bump...

**Comment by aquaductape** [comment]
I installed node canvas, `npm install canvas`, and I still have the same error

**Comment by Pardeep94** [comment]
@ca-miked I am facing same issue, do you find any solution for same ?

**Comment by hamzox** [comment]
Facing the same issue, any luck here? :'(

**Comment by Mickaz89** [comment]
same issue

**Comment by aayush27** [comment]
Same issue
