### ISSUE TITLE
create react app homepage 

### ISSUE THREAD

**Issue by johnny88** [geelen/react-snapshot#14]
Hey,

I am not sure if this falls under the category of *Is starting at / and crawling sufficient? Might there be unreachable sections of your site?*  but when I tried using the homepage option in package json from create react app build I am getting an error: 

```bash
Error: Uncaught [SyntaxError: Unexpected token <]
    at reportException (/opt/app/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:11)
    at /opt/app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:107:12
    at wrappedEnqueued (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/opt/app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13) SyntaxError: Unexpected token <
    at Object.exports.runInContext (vm.js:66:16)
    at processJavaScript (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/opt/app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:88:11)
    at /opt/app/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:107:12
    at wrappedEnqueued (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/opt/app/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/opt/app/node_modules/request/request.js:187:22)
    at emitTwo (events.js:106:13)
```
Everything seems to work without the homepage flag.

My app isn't so big so I could probably go in and redo the differences performed by the build script.

Once again this might fall under the aforementioned caveat, though it seems like a caveat that can be easily handled by parsing out the package json and maybe making a few edits to the server function. (i.e. still no configs of your own!)

Let me know what you think!

**Comment by johnny88** [comment]
Now that I think about it, the solution to that problem is going to be a bit more complex than just updating the server dir.

**Comment by johnny88** [comment]
Okay so this can be fixed in many cases with "homepage": "./"!

**Comment by JulesAU** [comment]
I also hacked together a fix to get this working for apps that are not hosted at "/" on a domain:

https://github.com/JulesAU/react-snapshot/commit/510c0f16b8facf4b11456da49086c0442ae29cc0

**Comment by AdeelK93** [comment]
@JulesAU have you considered submitting a PR? This would be great for lots of people!
