### ISSUE TITLE
react-snapshot crawl fails

### ISSUE THREAD

**Issue by cezarneaga** [geelen/react-snapshot#15]
console error below. 
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::2999
    at Object.exports._errnoException (util.js:1033:11)
    at exports._exceptionWithHostPort (util.js:1056:20)
    at Server._listen2 (net.js:1270:14)
    at listen (net.js:1306:10)
    at Server.listen (net.js:1397:7)
    at Function.listen (.../node_modules/connect/index.js:217:24)
    at Object.start (.../node_modules/pushstate-server/index.js:44:16)
    at .../node_modules/react-snapshot/lib/Server.js:26:52
    at Server.start (.../node_modules/react-snapshot/lib/Server.js:25:14)
    at exports.default (.../node_modules/react-snapshot/lib/cli.js:31:10)
error Command failed with exit code 1.
```

on now.sh i get this error:
```
at Url.parse (url.js:95:11)
>     at urlParse (url.js:89:5)
>     at Url.resolve (url.js:657:29)
>     at Object.urlResolve [as resolve] (url.js:653:40)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:96:44
>     at Array.forEach (native)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:88:83
>     at Array.forEach (native)
>     at Crawler.extractNewLinks (/home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:86:36)
>     at /home/nowuser/src/node_modules/react-snapshot/lib/Crawler.js:68:15
```

**Comment by cezarneaga** [comment]
on further investigating, it seems it cannot work if you have anchors as links

**Comment by JulesAU** [comment]
This worked for me:
https://github.com/JulesAU/react-snapshot/commit/1191635771694dff517449f9afa692cd08833734

**Comment by cezarneaga** [comment]
nope. doesnt do it :)

**Comment by arnibarnason** [comment]
I changed some `<a href="#"...>` to `<a>` and that fixed it for me.

**Comment by cezarneaga** [comment]
i need the linksmine are `#services` etc..

**Comment by bkeating** [comment]
I applied JulesAU/react-snapshot@1191635 and also removed all `href="#"` just in case. Im still getting held up with `TypeError: Parameter "url" must be a string, not object`. Is there a way I can turn on debug/verbose output to learn more?

**Comment by tedlin182** [comment]
Removing any `#` from the `href` resolved this issue for me. That seemed to be the main culprit

**Comment by geelen** [comment]
Can you please try again with `v1.1.0` released last night?
