### ISSUE TITLE
Error during build: Network request failed

### ISSUE THREAD

**Issue by marr** [geelen/react-snapshot#43]
I am trying to build a static site out from a create-react-app project, and I get the following error when I run 'npm run build'
>
[HPM] Proxy created: /  ->  http://localhost:3001
🕷   Starting crawling http://localhost:60815/
✏️   Saving / as /index.html
🕸   Finished crawling.
(node:25895) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Network request failed
(node:25895) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by sommcz** [comment]
I have similiar experience. Additionally my components renders only after some initial network fetch.
Is possible to make these network fetches before react-snapshot grabs the HTML form?
thank you
p.

**Comment by auser** [comment]
I see this bug as well.

**Comment by lmuntaner** [comment]
I have the same problem

**Comment by stereobooster** [comment]
Can you create small example repo with this error?

**Comment by socketwiz** [comment]
I'm getting a similar error as well.  It was not happening at first but as I continued to implement my app I introduced something that started triggering it.  I've tracked it down to a `fetch()` call I'm doing in `componentWillMount` of my component.

The full output of the error:

```
[HPM] Proxy created: /  ->  http://localhost:8000/
🕷   Starting crawling http://localhost:44385/
✏️   Saving / as /index.html
TypeError: Network request failed
    at XMLHttpRequest.i.onerror (http://localhost:44385/static/js/main.ff8c4eae.js:1:10723)
    at XMLHttpRequest.callback.(anonymous function) (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:289:32)
    at invokeEventListeners (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:219:27)
    at invokeInlineListeners (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:166:7)
    at EventTargetImpl._dispatch (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:122:7)
    at EventTargetImpl.dispatchEvent (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
    at XMLHttpRequest.dispatchEvent (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:61:35)
    at XMLHttpRequest.abort (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:405:16)
    at Object.abort (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:315:13)
    at RequestManager.close (/home/socketwiz/dev/Zolmok/frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:146:21)
```

The fetch call that is causing the problem:

```javascript
const mapDispatchToProps = dispatch => {
    return {
        'getPosts': () => {
            return fetch('/api/Posts')
                .then(checkStatus)
                .then(fetchJSON)
                .then(posts => {
                    if (posts) {
                        dispatch(getPosts(posts));
                    }
                })
                .catch(error => {
                    console.error(error);
                });
        }
    };
};
```

If I comment out the `getPosts` call the error goes away.
