### ISSUE TITLE
only get 200.html , but no other pages. I have no idea what to do @@

### ISSUE THREAD

**Issue by chunpin** [geelen/react-snapshot#53]
Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

File sizes after gzip:

  147.55 KB  build/static/js/main.6cbd44b6.js
  15.12 KB   build/static/css/main.d0134822.css

The project was built assuming it is hosted at the server root.
To override this, specify the homepage in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

🕷   Starting crawling http://localhost:64801/
Error: Uncaught [SyntaxError: Unexpected token <]
    at reportException (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13) SyntaxError: Unexpected token <
    at createScript (vm.js:56:10)
    at Object.runInContext (vm.js:88:10)
    at processJavaScript (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:128:10)
    at HTMLScriptElementImpl._eval (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/request/request.js:188:22)
Error: Uncaught [TypeError: Cannot read property 'fn' of undefined]
    at reportException (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/binny/Desktop/Big-Project/projs/batchfield-react/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13) TypeError: Cannot read property 'fn' of undefined
    at eval (webpack:///./src/owl.carousel.js?:1667:3)
    at eval (webpack:///./src/owl.carousel.js?:1701:3)
    at Object.<anonymous> (http://localhost:64801/static/js/main.6cbd44b6.js:1:432398)
    at e (http://localhost:64801/static/js/main.6cbd44b6.js:1:420602)
    at eval (webpack:///./components/OwlCarousel.jsx?:23:1)
    at Object.<anonymous> (http://localhost:64801/static/js/main.6cbd44b6.js:1:420741)
    at e (http://localhost:64801/static/js/main.6cbd44b6.js:1:420602)
    at http://localhost:64801/static/js/main.6cbd44b6.js:1:420689
    at http://localhost:64801/static/js/main.6cbd44b6.js:1:420694
    at n.(anonymous function).exports (http://localhost:64801/static/js/main.6cbd44b6.js:1:420314)
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
🕸   Finished crawling.

**Comment by stereobooster** [comment]
Please provide small application where it is possible to reproduce error
