### ISSUE TITLE
Cannot read 'map' of undefined

### ISSUE THREAD

**Issue by gecko25** [geelen/react-snapshot#63]
When I try to build my project, I am getting an error.  I am definitely calling the react-snapshot `render` function (instead of ReactDOM.render()

I am trying to hunt down the code where it occurs, but am having trouble interpreting since its the bundled code. I tried building with my dev config, but that cause even more errors. 

Any ideas / suggestions on how to proceed? 

```
🕷   Starting crawling http://localhost:64362/
✏️   Saving / as /index.html
✏️   Saving /en/ as /en/index.html
Error: Uncaught [TypeError: Cannot read property 'map' of undefined]
    at reportException (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/sara/Repositories/tablet-frontend/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/sara/Repositories/tablet-frontend/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13) TypeError: Cannot read property 'map' of undefined
    at a (http://localhost:64362/static/js/main-react.08b020e2.js:1:625919)
    at T (http://localhost:64362/static/js/main-react.08b020e2.js:1:641974)
    at _constructComponentWithoutOwner (http://localhost:64362/static/js/main-react.08b020e2.js:1:1447254)
    at _constructComponent (http://localhost:64362/static/js/main-react.08b020e2.js:1:1447108)
    at mountComponent (http://localhost:64362/static/js/main-react.08b020e2.js:1:1446289)
    at Object.mountComponent (http://localhost:64362/static/js/main-react.08b020e2.js:1:94471)
    at performInitialMount (http://localhost:64362/static/js/main-react.08b020e2.js:1:1448063)
    at mountComponent (http://localhost:64362/static/js/main-react.08b020e2.js:1:1446949)
    at Object.mountComponent (http://localhost:64362/static/js/main-react.08b020e2.js:1:94471)
    at performInitialMount (http://localhost:64362/static/js/main-react.08b020e2.js:1:1448063)
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
🕸   Finished crawling.
```

**Comment by arnaudambro** [comment]
Hi there, I have the same issue as you : I used window.location.pathname as a condition. If you don't use the window object, what do you use instead ?
