### ISSUE TITLE
react-snapshot v2 randomly fails during build

### ISSUE THREAD

**Issue by mattvox** [geelen/react-snapshot#75]
I've been having an issue with random build failures using v2. The fix simply appears to be running the build over and over again until it succeeds, which isn't a great solution when it comes to CI. The error appears to be completely jsdom related.

11:35:33 AM: 🕷   Starting crawling http://localhost:52537/
11:35:34 AM: { '0': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '1': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '2': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } } }
11:35:34 AM: ✏️   Saving / as /index.html
11:35:34 AM: [warning] Connection error occurred. Waiting for 2079 ms before retrying...
11:35:35 AM: { '0': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '1': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '2': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } } }
11:35:35 AM: ✏️   Saving /books/emma as /books/emma.html
11:35:36 AM: [warning] Connection error occurred. Waiting for 1932 ms before retrying...
11:35:36 AM: { '0': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '1': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } },
  '2': 
   { success: 
      { sys: [Object],
        total: 1,
        skip: 0,
        limit: 100,
        items: [Object],
        includes: [Object] } } }
11:35:36 AM: ✏️   Saving /contact as /contact.html
11:35:36 AM: 🕸   Finished crawling.
11:35:37 AM: [warning] Connection error occurred. Waiting for 2514 ms before retrying...
11:35:37 AM: [warning] Connection error occurred. Waiting for 2681 ms before retrying...
11:35:39 AM: /opt/build/repo/node_modules/jsdom/lib/jsdom/browser/Window.js:148
      return idlUtils.wrapperForImpl(idlUtils.implForWrapper(window._document)._location);
                                                                              ^

TypeError: Cannot read property '_location' of null
    at Window.get location [as location] (/opt/build/repo/node_modules/jsdom/lib/jsdom/browser/Window.js:148:79)
    at Timeout.callback [as _onTimeout] (/opt/build/repo/node_modules/jsdom/lib/jsdom/browser/Window.js:525:40)
    at ontimeout (timers.js:386:11)
    at tryOnTimeout (timers.js:250:5)
    at Timer.listOnTimeout (timers.js:214:5)
11:35:39 AM: error Command failed with exit code 1.
11:35:39 AM: Cached NPM modules
11:35:39 AM: Saved Yarn cache
11:35:40 AM: Build complete: exit code: 1
11:35:40 AM: Cleaning up docker container
11:35:41 AM: Error running command: Build script returned non-zero exit code: 1
11:35:41 AM: An error occurred while building the site, skipping the deploy and cache refresh.
11:35:41 AM: Build script returned non-zero exit code: 1
11:35:48 AM: Finished processing build request in 4m22.765341243s

**Comment by geelen** [comment]
Yeah v2 is very much a WIP, sorry. Thanks for the bug report I'll see if I can figure it out when I'm next working on it.
