### ISSUE TITLE
Issue running yarn build.

### ISSUE THREAD

**Issue by patwalls** [geelen/react-snapshot#79]
I can't seem to find anything about this here. Any steps to debug?
```
🕷   Starting crawling http://localhost:62284/
Error: Uncaught [TypeError: Cannot read property 'object' of undefined]
    at reportException (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at e (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22)
    at Object.check (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at /Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/Users/pwalls/src/starter-story/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (/Users/pwalls/src/starter-story/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13) TypeError: Cannot read property 'object' of undefined
    at http://localhost:62284/static/js/main.f8e2d949.js:1:109926
    at Object.<anonymous> (http://localhost:62284/static/js/main.f8e2d949.js:1:110680)
    at t (http://localhost:62284/static/js/main.f8e2d949.js:1:101)
    at Object.<anonymous> (http://localhost:62284/static/js/main.f8e2d949.js:1:221950)
    at t (http://localhost:62284/static/js/main.f8e2d949.js:1:101)
    at Object.<anonymous> (http://localhost:62284/static/js/main.f8e2d949.js:1:136642)
    at t (http://localhost:62284/static/js/main.f8e2d949.js:1:101)
    at Object.<anonymous> (http://localhost:62284/static/js/main.f8e2d949.js:1:125989)
    at t (http://localhost:62284/static/js/main.f8e2d949.js:1:101)
    at http://localhost:62284/static/js/main.f8e2d949.js:1:452
🔥 'render' from react-snapshot was never called. Did you replace the call to ReactDOM.render()?
🕸   Finished crawling.
Done in 15.59s.
```

**Comment by patwalls** [comment]
This turned out to be an issue with react-helmet package. I was using an old version v4.
