### ISSUE TITLE
Error: matchMedia not present, legacy browsers require a polyfill

### ISSUE THREAD

**Issue by romkacrv** [geelen/react-snapshot#98]
Starting crawling http://localhost:46865/

Error: Uncaught [Error: matchMedia not present, legacy browsers require a polyfill]
    at reportException (node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:58:24)
    at processJavaScript (node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:130:7)
    at HTMLScriptElementImpl._eval (node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/living/nodes/HTMLScriptElement-impl.js:65:7)
    at node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:31:22
    at Object.check node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:89:11)
    at node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/living/nodes/Document-impl.js:108:12
    at wrappedEnqueued (node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:255:16)
    at Request.request [as _callback] (/node_modules/react-snapshot/node_modules/jsdom/lib/jsdom/browser/resource-loader.js:203:9)
    at Request.self.callback (node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13) Error: matchMedia not present, legacy browsers require a polyfill

An error appear while using react-snapshot, any suggestion ?

**Comment by PDS42** [comment]
Just had the same issue after following the three steps of the repository. Is there a known fix for this ?

**Comment by balazsorban44** [comment]
Same issue here

**Comment by romkacrv** [comment]
tried https://github.com/akiran/react-slick/issues/472, did not help

**Comment by baomastr** [comment]
having the same trouble

**Comment by baomastr** [comment]
@romkacrv if you run `npm run eject` and paste polyfill that mentioned in issue https://github.com/akiran/react-slick/issues/742#issuecomment-298992238 into `config/polyfills.js` it will solve the problem.

**Comment by stefankp** [comment]
I am having the same issue. The polyfill mentioned by @baomastr does not solve it.

**Comment by nimahkh** [comment]
same issue

**Comment by ZengTianShengZ** [comment]
same issue

**Comment by zernabhussain** [comment]
check this: https://github.com/akiran/react-slick/issues/742#issuecomment-557793922
